name: β¨ Feature Request
description: μƒλ΅μ΄ κΈ°λ¥ λλ” κ°μ„ μ‚¬ν•­μ„ μ μ•ν•©λ‹λ‹¤
title: "[REQUEST] "
labels:
  - enhancement
assignees: []

body:
  - type: markdown
    attributes:
      value: |
      
        ### μ μ•ν•κΈ° μ „μ— μ•„λ λ‚΄μ©μ„ ν™•μΈν•΄μ£Όμ„Έμ”:
        - ν„μ¬ μ΅΄μ¬ν•μ§€ μ•λ” κΈ°λ¥μ„μ„ ν™•μΈν–μµλ‹λ‹¤.
        - μ μ•ν•λ” λ…ν™•ν• μ΄μ κ°€ μ΅΄μ¬ν•©λ‹λ‹¤.
        - μ λ©μ΄ μ μ•μ λ‚΄μ©μ„ μ ν‘ν„ν•κ³  μμµλ‹λ‹¤.

  - type: textarea
    attributes:
      label: π“„ μ„¤λ…
      description: μ μ•ν•κ³  μ‹¶μ€ λ‚΄μ©μ„ μμ„Έν μ„¤λ…ν•΄μ£Όμ„Έμ”.
    validations:
      required: true

  - type: textarea
    attributes:
      label: π‘π» μ¶”κ°€ μ •λ³΄
      description: μ μ•κ³Ό κ΄€λ ¨λ μ¶”κ°€ μ •λ³΄λ¥Ό μ…λ ¥ν•΄μ£Όμ„Έμ”. (μ„ νƒ μ‚¬ν•­)
